<template>
  <my-table :rows="rows" :columns="columns">
  </my-table>
<!--  <tes-two></tes-two>-->
<!--  <HelloWorld msg="Welcome to Your Vue.js App"/>-->
<!--  <test-one></test-one>-->
<!--  <table-component :rows="rows" :columns="columns"></table-component>-->
</template>

<script>
// import testOne from "@/components/testOne.vue";
// import TableComponent from "@/Table/TableComponent";
import MyTable from "@/Table/my-table.vue";
// import TesTwo from "@/components/test2.vue";

export default {
  name: 'App',
  components: {
    // TesTwo,
    MyTable
    // TableComponent,
    // HelloWorld,
  },
  data() {
    return {
      columns: [
        { field: 'id', title: 'ID' },
        { field: 'name', title: 'Name' },
        { field: 'email', title: 'Email' },
        { field: 'sex', title: 'Sex' },
        { field: 'score', title: 'Score' },
        { field: 'home', title: 'Home' },
        { field: 'age', title: 'Age' },
        { field: 'hobby', title: 'Hobby' },
        { field: 'height', title: 'Height' },
        { field: 'weight', title: 'Weight' },
      ],
      rows: [
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
        { id: 1, name: 'John Doe', email: 'johndoe@example.com',sex:'男',score:90,home:'shanghai',age:'18',hobby:'music',height:'180',weight:'70' },
        { id: 2, name: 'Jane Doe', email: 'janedoe@example.com' ,sex:'男',score:91,home:'shanghai',age:'17',hobby:'movie',height:'178',weight:'76'},
        { id: 3, name: 'Bob Smith', email: 'bobsmith@example.com',sex:'女',score:96,home:'nanjing',age:'18',hobby:'table-tennis',height:'170',weight:'50' },
      ]
    }
  }
}
</script>

<style>

</style>
