<template>
  <!--    <my-table :rows="rows" :columns="columns">-->
  <!--    <template #inputName="{row}">-->
  <!--      <vxe-select v-model="row.age" placeholder="默认尺寸">-->
  <!--        <vxe-option v-for="num in 15" :key="num" :value="num" :label="`选项${num}`"></vxe-option>-->
  <!--      </vxe-select>-->
  <!--    </template>-->
  <!--    </my-table>-->

  <!--  <my-table-demo :rows="rows" :columns="columns" >-->
  <!--  <test-one></test-one>-->
  <!--  </my-table-demo>-->

  <test-one />
  <TableComponent
    :rows="row"
    :columns="columns"
    :colTypes="colTypes"
    :flyweight="true"
  >
    <template #input="{ row }">
      <vxe-select v-model="row.age" placeholder="默认尺寸">
        <vxe-option
          v-for="num in 100"
          :key="num"
          :value="num"
          :label="`${num}`"
        ></vxe-option>
      </vxe-select>
    </template>
  </TableComponent>

  <!--  <table-component :rows="newRows" :columns="columns">-->
  <!--&lt;!&ndash;    循环row，划分列&ndash;&gt;-->
  <!--  </table-component>-->
</template>

<script setup>
// import TableComponent from "@/Table/TableComponent";
import { reactive, ref } from "vue";

import MyTable from "@/my-table/my-table.vue";
import flyWeight from "@/FlyWeight";
let sizeof = require("object-sizeof");
import TableComponent from "./Table2/TableComponent";
import TestOne from "@/components/testOne.vue";

// import TableComponent from "@/Table/TableComponent";
// import test from "./test";
// import TableComponent from "@/test";
// import MyTableDemo from "@/my-table/my-table-demo.vue";
let colTypes = reactive(["input", "select"]);
let columns = reactive([
  { field: "id", title: "ID", type: "input" },
  { field: "name", title: "Name", type: "select" },
  { field: "email", title: "Email", type: "input" },
  { field: "sex", title: "Sex", type: "select" },
  { field: "score", title: "Score", type: "input" },
  { field: "home", title: "Home", type: "select" },
  { field: "age", title: "Age", type: "input" },
  { field: "hobby", title: "Hobby", type: "select" },
  { field: "height", title: "Height", type: "input" },
  { field: "weight", title: "Weight", type: "input" },
]);
let rowHalf = reactive([
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
]);
let row = reactive([
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    sex: "男",
    score: 90,
    home: "shanghai",
    age: "18",
    hobby: "music",
    height: "180",
    weight: "70",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@example.com",
    sex: "男",
    score: 91,
    home: "shanghai",
    age: "17",
    hobby: "movie",
    height: "178",
    weight: "76",
  },
  {
    id: 3,
    name: "Bob Smith",
    email: "bobsmith@example.com",
    sex: "女",
    score: 96,
    home: "nanjing",
    age: "18",
    hobby: "table-tennis",
    height: "170",
    weight: "50",
  },
]);
// console.log(sizeof(rows), sizeof(row));
// console.log(rows, row);
console.log(row);
// let newRows = reactive(Array(rows.length).fill(0).map(()=> new Object()))

// console.log(factory,newRows)
</script>
